global:
  resolve_timeout: 1m
  smtp_smarthost: 'smtp.yandex.ru:587'
  smtp_from: 'd1g1texavds@yandex.ru'
  smtp_auth_username: 'd1g1texavds@yandex.ru'
  smtp_auth_password: 'fqohustfnmyezmru'
  smtp_require_tls: true

route:
  receiver: 'critical-receiver'
  group_by: ['service', 'severity']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

  routes:
    # Маршрут для критических алертов
    - match:
        severity: critical
      receiver: 'critical-receiver'
      group_wait: 10s
      group_interval: 2m
      repeat_interval: 1h

    # Маршрут для предупреждений
    - match:
        severity: warning
      receiver: 'warning-receiver'
      group_interval: 10m
      repeat_interval: 6h

receivers:
  - name: 'critical-receiver'
    email_configs:
      - to: 'd1g1texavds@yandex.ru'
        headers:
          subject: '{{ if eq .Status "firing" }}[CRITICAL] {{ .GroupLabels.alertname }} на {{ .CommonLabels.instance }}{{ else }}[RESOLVED] {{ .GroupLabels.alertname }} на {{ .CommonLabels.instance }}{{ end }}'

  - name: 'warning-receiver'
    email_configs:
      - to: 'd1g1texavd@gmail.com'
        headers:
          subject: '{{ if eq .Status "firing" }}[WARNING] {{ .GroupLabels.alertname }} на {{ .CommonLabels.instance }}{{ else }}[RESOLVED] {{ .GroupLabels.alertname }} на {{ .CommonLabels.instance }}{{ end }}'
