metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
  enabled: true
  period: 10s

output.elasticsearch:
  hosts: ["http://192.168.1.15:9200"]
  username: "elastic"
  password: "GvNjrX0MzqZ_QdTE7FgN"

setup.kibana:
  host: "http://192.168.1.15:5601"
  username: "elastic"
  password: "GvNjrX0MzqZ_QdTE7FgN"
