# Metricbeat Configuration
metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - diskio
    - filesystem
    - fsstat
  enabled: true
  period: 10s
  processes: ['.*']

- module: nginx
  metricsets: ["stubstatus"]
  enabled: true
  period: 10s
  hosts: ["http://127.0.0.1/nginx_status"]

- module: mysql
  metricsets: ["status"]
  enabled: true
  period: 10s
  hosts: ["tcp(127.0.0.1:3306)/"]
  username: root
  password: ""

output.elasticsearch:
  hosts: ["192.168.1.11:9200"]
  indices:
    - index: "metricbeat-%{[service.name]}-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.kibana:
  host: "192.168.1.11:5601"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat.log
  keepfiles: 7
