global:
  scrape_interval: 5s

scrape_configs:

# Node Exporter
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.12:9090']

# Node Exporter
  - job_name: 'node_exporter_centos'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.12:9100']

# Node Exporter
  - job_name: 'node_exporter_ubuntu'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.13:9100']

# MySQL Exporter
  - job_name: 'mysql-cms'
    static_configs:
      - targets: ['192.168.1.13:9104']

# NGINX Exporter
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["192.168.1.13:9113"]

# PHP-FPM Exporter
  - job_name: 'php-fpm'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.13:9253']
    metrics_path: /metrics

# Blackbox Exporter
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://192.168.1.13
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.13:9115
